### ISSUE TITLE
Create initial README

### ISSUE THREAD

**Issue by carltonwhitehead** [caeos/coner-drs#4]
At minimum, describe project purpose and build instructions

**Comment by fellahi-ali** [comment]
Exactly ;) that would be very helpful!

Anyway! thank you very much! for https://kotlinlang.slack.com/archives/C136UUPE1/p1554639931065700?thread_ts=1554617072.065500&cid=C136UUPE1

I hope I can help you with this and send you a PR when I understand it :)
