### ISSUE TITLE
Running the app from IntelliJ requires Maven build step customization

### ISSUE THREAD

**Issue by carltonwhitehead** [caeos/coner-drs#54]
Reconfigure the property resource file generator to build from an early enough step that the default IntelliJ run configuration will trigger it.

The symptom is the app crashes at launch due to a missing properties resource file.

**Comment by carltonwhitehead** [comment]
I looked into this. Not as simple as I first thought.

Running the Kotlin class just runs the project through kotlinc. That means it doesn't execute Maven, so none of the expected resources get generated.

There is a javafx Maven plugin for Java 8, but it's an abandoned side project and didn't seem like it rose to the level of being our recommended way to start the project.

There is a JavaFX 11+ Maven plugin, but that requires migrating to TornadoFX 2 (not yet released). 

Considering all of tthe above, I think we should just include the IntelliJ config guidance for generating resources.

**Comment by DannyAllegrezza** [comment]
> I looked into this. Not as simple as I first thought.
> 
> Running the Kotlin class just runs the project through kotlinc. That means it doesn't execute Maven, so none of the expected resources get generated.
> 
> There is a javafx Maven plugin for Java 8, but it's an abandoned side project and didn't seem like it rose to the level of being our recommended way to start the project.
> 
> There is a JavaFX 11+ Maven plugin, but that requires migrating to TornadoFX 2 (not yet released).
> 
> Considering all of tthe above, I think we should just include the IntelliJ config guidance for generating resources in the readme.

I can take a stab at updating the README to include the guidance we discussed previously.

**Comment by carltonwhitehead** [comment]
That would be very helpful, thanks Danny!
